title: tharakadevinda.github.io
logo: /assets/img/headshot_circle.png
description: "A modern professional profile of Tharaka Devinda"
show_downloads: true
theme: jekyll-theme-minimal

# Add custom settings
author: Tharaka Devinda
email: your.email@example.com
linkedin: https://www.linkedin.com/in/tharakadevinda/
github: https://github.com/tharakadevinda
twitter: https://twitter.com/tharakadevinda

# Theme customizations
minimal:
  accent_color: "#083c74" # Your preferred accent color
  base_color: "#f0f0f0" # Background color
  text_color: "#333" # Text color
